import IGuild from "../interfaces/ApiGuild";
import Emoji from "./Emoji";
import Role from "./Role";
import Sticker from "./Sticker";
import WelcomeScreen from "./WelcomeScreen";

export default class Guild {
    
    public afkChannelId: string | null;
    public afkTimeout: number;
    public applicationId: string | null;
    public approximateMemberCount: number | null;
    public approximatePresenceCount: number | null;
    public banner: string | null;
    public defaultMessageNotifications: number;
    public description: string | null;
    public discoverySplash: string | null;
    public emojis: Emoji[];
    public explicitContentFilter: number;
    public features: string[];
    public icon: string | null;
    public iconHash: string | null;
    public id: string;
    public maxMembers: number | null;
    public maxPresences: number | null;
    public maxStageVideoChannelUsers: number | null;
    public maxVideoChannelUsers: number | null;
    public mfaLevel: number;
    public name: string;
    public nsfwLevel: number;
    public owner: boolean;
    public ownerId: string;
    public permissions: string | null;
    public preferredLocale: string;
    public premiumProgressBarEnabled: boolean;
    public premiumSubscriptionCount: number | null;
    public premiumTier: number;
    public publicUpdatesChannelId: string | null;
    public region: string | null;
    public roles: Role[];
    public rulesChannelId: string | null;
    public safetyAlertsChannelId: string | null;
    public splash: string | null;
    public stickers: Sticker[] | undefined;
    public systemChannelFlags: number;
    public systemChannelId: string | null;
    public vanityUrlCode: string | null;
    public verificationLevel: number;
    public welcomeScreen: WelcomeScreen | null;
    public widgetChannelId: string | null;
    public widgetEnabled: boolean;

    constructor(data: IGuild) {
        this.afkChannelId = data.afk_channel_id;
        this.afkTimeout = data.afk_timeout;
        this.applicationId = data.application_id;
        this.approximateMemberCount = data.approximate_member_count ?? null;
        this.approximatePresenceCount = data.approximate_presence_count ?? null;
        this.banner = data.banner;
        this.defaultMessageNotifications = data.default_message_notifications;
        this.description = data.description;
        this.discoverySplash = data.discovery_splash;
        this.emojis = data.emojis.map((emoji) => new Emoji(emoji));
        this.explicitContentFilter = data.explicit_content_filter;
        this.features = data.features;
        this.icon = data.icon;
        this.iconHash = data.icon_hash ?? null;
        this.id = data.id;
        this.maxMembers = data.max_members ?? null;
        this.maxPresences = data.max_presences ?? null;
        this.maxStageVideoChannelUsers = data.max_stage_video_channel_users ?? null;
        this.maxVideoChannelUsers = data.max_video_channel_users ?? null;
        this.mfaLevel = data.mfa_level;
        this.name = data.name;
        this.nsfwLevel = data.nsfw_level;
        this.owner = !!data.owner;
        this.ownerId = data.owner_id;
        this.permissions = data.permissions ?? null;
        this.preferredLocale = data.preferred_locale;
        this.premiumProgressBarEnabled = data.premium_progress_bar_enabled;
        this.premiumSubscriptionCount = data.premium_subscription_count ?? null;
        this.premiumTier = data.premium_tier;
        this.publicUpdatesChannelId = data.public_updates_channel_id;
        this.region = data.region ?? null;
        this.roles = data.roles.map((role) => new Role(role));
        this.rulesChannelId = data.rules_channel_id;
        this.safetyAlertsChannelId = data.safety_alerts_channel_id;
        this.splash = data.splash;
        this.stickers = data.stickers?.map((sticker) => new Sticker(sticker));
        this.systemChannelFlags = data.system_channel_flags;
        this.systemChannelId = data.system_channel_id;
        this.vanityUrlCode = data.vanity_url_code;
        this.verificationLevel = data.verification_level;
        this.welcomeScreen = data.welcome_screen ? new WelcomeScreen(data.welcome_screen) : null;
        this.widgetChannelId = data.widget_channel_id ?? null;
        this.widgetEnabled = !!data.widget_enabled;
    }
}