"use client";
import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className = "w-screen h-screen"}>
        <ThemeProvider>
          <div className='bg-background text-foreground w-full h-full'>
            <Navbar />
            <div className='w-full h-[calc(100%-4rem)] fixed mt-[4rem] overflow-auto'>
              {children}
            </div>
          </div>
        </ThemeProvider>

      </body>
    </html>
  )
}
