"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OAuth2Scope = void 0;
var OAuth2Scope;
(function (OAuth2Scope) {
    OAuth2Scope["ActivitiesRead"] = "activities.read";
    OAuth2Scope["ActivitiesWrite"] = "activities.write";
    OAuth2Scope["ApplicationsBuildsRead"] = "applications.builds.read";
    OAuth2Scope["ApplicationsBuildsUpload"] = "applications.builds.upload";
    OAuth2Scope["ApplicationsCommands"] = "applications.commands";
    OAuth2Scope["ApplicationsCommandsUpdate"] = "applications.commands.update";
    OAuth2Scope["ApplicationsCommandsPermissionsUpdate"] = "applications.commands.permissions.update";
    OAuth2Scope["ApplicationsEntitlements"] = "applications.entitlements";
    OAuth2Scope["ApplicationsStoreUpdate"] = "applications.store.update";
    OAuth2Scope["Bot"] = "bot";
    OAuth2Scope["Connections"] = "connections";
    OAuth2Scope["DmChannelsRead"] = "dm_channels.read";
    OAuth2Scope["Email"] = "email";
    OAuth2Scope["GdmJoin"] = "gdm.join";
    OAuth2Scope["Guilds"] = "guilds";
    OAuth2Scope["GuildsJoin"] = "guilds.join";
    OAuth2Scope["GuildsMembersRead"] = "guilds.members.read";
    OAuth2Scope["Identify"] = "identify";
    OAuth2Scope["MessagesRead"] = "messages.read";
    OAuth2Scope["RelationshipsRead"] = "relationships.read";
    OAuth2Scope["RoleConnectionsRead"] = "role_connections.write";
    OAuth2Scope["Rpc"] = "rpc";
    OAuth2Scope["RpcActivitiesWrite"] = "rpc.activities.write";
    OAuth2Scope["RpcNotificationsRead"] = "rpc.notifications.read";
    OAuth2Scope["RpcVoiceRead"] = "rpc.voice.read";
    OAuth2Scope["RpcVoiceWrite"] = "rpc.voice.write";
    OAuth2Scope["Voice"] = "voice";
    OAuth2Scope["WebhookIncoming"] = "webhook.incoming";
})(OAuth2Scope || (exports.OAuth2Scope = OAuth2Scope = {}));
