"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WelcomeScreen = exports.WebsocketClient = exports.User = exports.ThreadChannel = exports.TeamMember = exports.Team = exports.StickerItem = exports.Sticker = exports.SolaceIntents = exports.SolaceError = exports.RoleSubscriptionData = exports.Role = exports.Registry = exports.ReactionCountDetails = exports.Reaction = exports.Plugin = exports.OpCodes = exports.Message = exports.Interaction = exports.GuildMember = exports.Guild = exports.GatewayIntents = exports.EventHandler = exports.Event = exports.Emoji = exports.EmbedVideo = exports.EmbedThumbnail = exports.EmbedProvider = exports.EmbedImage = exports.EmbedFooter = exports.EmbedField = exports.EmbedAuthor = exports.Embed = exports.Constants = exports.Client = exports.Channel = exports.Attachment = exports.ApplicationInstallParams = exports.Application = exports.Activity = void 0;
const Activity_1 = __importDefault(require("./structures/Activity"));
exports.Activity = Activity_1.default;
const Application_1 = __importStar(require("./structures/Application"));
exports.Application = Application_1.default;
Object.defineProperty(exports, "ApplicationInstallParams", { enumerable: true, get: function () { return Application_1.ApplicationInstallParams; } });
const Attachment_1 = __importDefault(require("./structures/Attachment"));
exports.Attachment = Attachment_1.default;
const Channel_1 = __importDefault(require("./structures/Channel"));
exports.Channel = Channel_1.default;
const Client_1 = __importDefault(require("./client/Client"));
exports.Client = Client_1.default;
const Constants_1 = __importDefault(require("./config/Constants"));
exports.Constants = Constants_1.default;
const Embed_1 = __importStar(require("./structures/Embed"));
exports.Embed = Embed_1.default;
Object.defineProperty(exports, "EmbedAuthor", { enumerable: true, get: function () { return Embed_1.EmbedAuthor; } });
Object.defineProperty(exports, "EmbedField", { enumerable: true, get: function () { return Embed_1.EmbedField; } });
Object.defineProperty(exports, "EmbedFooter", { enumerable: true, get: function () { return Embed_1.EmbedFooter; } });
Object.defineProperty(exports, "EmbedImage", { enumerable: true, get: function () { return Embed_1.EmbedImage; } });
Object.defineProperty(exports, "EmbedProvider", { enumerable: true, get: function () { return Embed_1.EmbedProvider; } });
Object.defineProperty(exports, "EmbedThumbnail", { enumerable: true, get: function () { return Embed_1.EmbedThumbnail; } });
Object.defineProperty(exports, "EmbedVideo", { enumerable: true, get: function () { return Embed_1.EmbedVideo; } });
const Emoji_1 = __importDefault(require("./structures/Emoji"));
exports.Emoji = Emoji_1.default;
const Event_1 = __importDefault(require("./helper/Event"));
exports.Event = Event_1.default;
const EventHandler_1 = __importDefault(require("./util/EventHandler"));
exports.EventHandler = EventHandler_1.default;
const GatewayIntents_1 = __importDefault(require("./config/GatewayIntents"));
exports.GatewayIntents = GatewayIntents_1.default;
const Guild_1 = __importDefault(require("./structures/Guild"));
exports.Guild = Guild_1.default;
const GuildMember_1 = __importDefault(require("./structures/GuildMember"));
exports.GuildMember = GuildMember_1.default;
const Interaction_1 = __importDefault(require("./structures/Interaction"));
exports.Interaction = Interaction_1.default;
const Message_1 = __importDefault(require("./structures/Message"));
exports.Message = Message_1.default;
const OpCodes_1 = __importDefault(require("./config/OpCodes"));
exports.OpCodes = OpCodes_1.default;
const Plugin_1 = __importDefault(require("./helper/Plugin"));
exports.Plugin = Plugin_1.default;
const Reaction_1 = __importStar(require("./structures/Reaction"));
exports.Reaction = Reaction_1.default;
Object.defineProperty(exports, "ReactionCountDetails", { enumerable: true, get: function () { return Reaction_1.ReactionCountDetails; } });
Object.defineProperty(exports, "RoleSubscriptionData", { enumerable: true, get: function () { return Reaction_1.RoleSubscriptionData; } });
const Registry_1 = __importDefault(require("./helper/Registry"));
exports.Registry = Registry_1.default;
const Role_1 = __importDefault(require("./structures/Role"));
exports.Role = Role_1.default;
const SolaceError_1 = __importDefault(require("./util/SolaceError"));
exports.SolaceError = SolaceError_1.default;
const SolaceIntents_1 = __importDefault(require("./config/SolaceIntents"));
exports.SolaceIntents = SolaceIntents_1.default;
const Sticker_1 = __importStar(require("./structures/Sticker"));
exports.Sticker = Sticker_1.default;
Object.defineProperty(exports, "StickerItem", { enumerable: true, get: function () { return Sticker_1.StickerItem; } });
const Team_1 = __importDefault(require("./structures/Team"));
exports.Team = Team_1.default;
const TeamMember_1 = __importDefault(require("./structures/TeamMember"));
exports.TeamMember = TeamMember_1.default;
const ThreadChannel_1 = __importDefault(require("./structures/ThreadChannel"));
exports.ThreadChannel = ThreadChannel_1.default;
const User_1 = __importDefault(require("./structures/User"));
exports.User = User_1.default;
const WebsocketClient_1 = __importDefault(require("./client/WebsocketClient"));
exports.WebsocketClient = WebsocketClient_1.default;
const WelcomeScreen_1 = __importDefault(require("./structures/WelcomeScreen"));
exports.WelcomeScreen = WelcomeScreen_1.default;
